export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'
export const SET_PROFILE = 'SET_PROFILE'

export const HOME_VIDEOS_REQUEST = 'HOME_VIDEOS_REQUEST'
export const HOME_VIDEOS_SUCCESS = 'HOME_VIDEOS_SUCCESS'
export const HOME_VIDEOS_FAILED = 'HOME_VIDEOS_FAILED'

export const SET_ACTIVE_CATEGORY = 'SET_ACTIVE_CATEGORY'
