export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'
export const SET_PROFILE = 'SET_PROFILE'

export const HOME_VIDEOS_REQUEST = 'HOME_VIDEOS_REQUEST'
export const HOME_VIDEOS_SUCCESS = 'HOME_VIDEOS_SUCCESS'
export const HOME_VIDEOS_FAILED = 'HOME_VIDEOS_FAILED'

export const SET_ACTIVE_CATEGORY = 'SET_ACTIVE_CATEGORY'

export const SELECTED_VIDEO_REQUEST = 'SELECTED_VIDEO_REQUEST'
export const SELECTED_VIDEO_SUCCESS = 'SELECTED_VIDEO_SUCCESS'
export const SELECTED_VIDEO_FAILED = 'SELECTED_VIDEO_FAILED'

export const CHANNEL_DETAILS_REQUEST = 'CHANNEL_DETAILS_REQUEST'
export const CHANNEL_DETAILS_SUCCESS = 'CHANNEL_DETAILS_SUCCESS'
export const CHANNEL_DETAILS_FAIL = 'CHANNEL_DETAILS_FAIL'

export const CHANNEL_SUBSCRIPTION_STATUS = 'CHANNEL_SUBSCRIPTION_STATUS'

export const LIST_COMMENTS_SUCCESS = 'LIST_COMMENTS_SUCCESS'
export const LIST_COMMENTS_FAIL = 'LIST_COMMENTS_FAIL'

export const CREATE_COMMENT_REQUEST = 'CREATE_COMMENT_REQUEST'
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS'
export const CREATE_COMMENT_FAILED = 'CREATE_COMMENT_FAILED'

export const SUBSCRIPTIONS_VIDEOS_REQUEST = 'SUBSCRIPTIONS_VIDEOS_REQUEST'
export const SUBSCRIPTIONS_VIDEOS_SUCCESS = 'SUBSCRIPTIONS_VIDEOS_SUCCESS'
export const SUBSCRIPTIONS_VIDEOS_FAILED = 'SUBSCRIPTIONS_VIDEOS_FAILED'

export const RELATED_VIDEOS_REQUEST = 'RELATED_VIDEOS_REQUEST'
export const RELATED_VIDEOS_SUCCESS = 'RELATED_VIDEOS_SUCCESS'
export const RELATED_VIDEOS_FAIL = 'RELATED_VIDEOS_FAIL'
