import firebase from 'firebase/app'
import 'firebase/auth'

const firebaseConfig = {
   apiKey: 'AIzaSyA3WLFo6oY5PnF6Pw0LZ75MsnyzWGTmCko',
   authDomain: 'yt-clone-again.firebaseapp.com',
   projectId: 'yt-clone-again',
   storageBucket: 'yt-clone-again.appspot.com',
   messagingSenderId: '1027598335261',
   appId: '1:1027598335261:web:7c0d2846fb3d713f89b5f4',
}

firebase.initializeApp(firebaseConfig)

// const provider = new firebase.auth.GoogleAuthProvider()
// provider.addScope("https://www.googleapis.com/auth/youtube.force-ssl")

// export const signInWithGoogle = async () => await auth.signInWithPopup(provider)

export default firebase.auth()

// Steps
// 1. create project
// 2. create app and copy config
// ----
// 3. enable google authentication ; it will create the google Secret ID and secret token
// 4. Enable API and get API key : https://console.developers.google.com/cloud-resource-manager
// 5 . Find project , click on 3 dots then settings

// GET THE API KEY : click on credentials ->copy the api key generated by firebase

//----ENABLE THE YOUTUBE API SERVICE
// 6. from navigation menu select api & service -> dashboard
// 7. Enable API and Service
// 8. search Youtube Data API 3 and enable this
// That's It
